#include <limits.h>
#include <algorithm>
#include <cmath>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <string>
#include <vector>
#include <unordered_map>
#include <unordered_set>

using namespace std;

// Problem Description:
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

int main() {
    int result = 0;
    int a = 1;
    int b = 1;
    int c = a + b;
    do {
        if (c % 2 == 0) {result += c;}
        a = b;
        b = c;
        c = a + b;
    } while (c <= 4000000);
    cout << result << endl;
}